// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCallInfo } from "./ToolCallInfo";

/**
 * A message in the conversation (UI-specific with serialization)
 */
export type ChatMessage = { id: string, role: string, content: string, tool_calls?: Array<ToolCallInfo>, timestamp: string, };
