// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single line in a diff preview
 */
export interface DiffLine {
  line_number: number | null
  line_type: "context" | "added" | "removed"
  content: string
}

/**
 * Context usage breakdown by category
 */
export interface ContextBreakdown {
  system_tokens: number
  conversation_tokens: number
  tool_tokens: number
  memory_tokens: number
  input_tokens: number
  output_tokens: number
}

/**
 * Context usage statistics
 */
export interface ContextUsage {
  used_tokens: number
  limit_tokens: number
  used_percentage: number
  remaining_tokens: number
  should_compact: boolean
  breakdown: ContextBreakdown
}

/**
 * Messages sent from loop to frontend
 * Now includes session_id for multi-session support
 */
export type LoopOutput =
  | { type: "ready"; session_id: string }
  | { type: "user_message"; session_id: string; id: string; content: string }
  | { type: "thinking"; session_id: string; content: string }
  | { type: "assistant_message"; session_id: string; id: string; content: string }
  | { type: "tool_start"; session_id: string; id: string; name: string; arguments: Record<string, unknown> }
  | { type: "tool_pending"; session_id: string; id: string; name: string; arguments: Record<string, unknown>; description?: string; subagent_id?: string }
  | { type: "tool_done"; session_id: string; id: string; name: string; success: boolean; output: string }
  | { type: "tool_call"; session_id: string; id: string; name: string; arguments: Record<string, unknown>; formatted: string }
  | { type: "tool_result"; session_id: string; id: string; name: string; success: boolean; output: string; summary: string; diff_preview: DiffLine[] | null }
  | { type: "question"; session_id: string; request_id: string; questions: Array<{ question: string; header: string | null; options: Array<{ label: string; description: string | null }>; multi_select: boolean }>; subagent_id?: string }
  | { type: "idle"; session_id: string }
  | { type: "error"; session_id: string; message: string }
  | { type: "stopped"; session_id: string }
  | { type: "cancelled"; session_id: string };
