// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Messages sent from loop to frontend
 * Now includes session_id for multi-session support
 */
export type LoopOutput =
  | { type: "ready"; session_id: string }
  | { type: "user_message"; session_id: string; id: string; content: string }
  | { type: "thinking"; session_id: string; content: string }
  | { type: "assistant_message"; session_id: string; id: string; content: string }
  | { type: "tool_start"; session_id: string; id: string; name: string; arguments: Record<string, unknown> }
  | { type: "tool_pending"; session_id: string; id: string; name: string; arguments: Record<string, unknown> }
  | { type: "tool_done"; session_id: string; id: string; name: string; success: boolean; output: string }
  | { type: "question"; session_id: string; request_id: string; questions: Array<{ question: string; header: string | null; options: Array<{ label: string; description: string | null }>; multi_select: boolean }> }
  | { type: "idle"; session_id: string }
  | { type: "error"; session_id: string; message: string }
  | { type: "stopped"; session_id: string };
