// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Messages sent from loop to frontend
 */
export type LoopOutput = { "type": "ready" } | { "type": "user_message", id: string, content: string, } | { "type": "thinking", content: string, } | { "type": "assistant_message", id: string, content: string, } | { "type": "tool_start", id: string, name: string, arguments: Record<string, unknown>, } | { "type": "tool_pending", id: string, name: string, arguments: Record<string, unknown>, } | { "type": "tool_done", id: string, name: string, success: boolean, output: string, } | { "type": "idle" } | { "type": "error", message: string, } | { "type": "stopped" };
