// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Loop states for the agentic execution
 */
export type LoopState = "idle" | "waiting_for_llm" | "waiting_for_approval" | "waiting_for_question" | "executing_tools" | "completed" | "cancelled" | "error";
