// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCallStatus } from "./ToolCallStatus";

/**
 * Tool call information for display (UI-specific with serialization)
 */
export type ToolCallInfo = { id: string, name: string, arguments: Record<string, unknown>, status: ToolCallStatus, result: string | null, };
