// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionOption } from "./QuestionOption";

/**
 * A question to ask the user
 */
export type UserQuestion = { question: string, header: string, options: Array<QuestionOption>, multi_select: boolean, };
